const InitialState = {
    leagues:{
                PremierLeague:
                {
                   id: 'eng.1',
                   imgUrl:'https://images.onefootball.com/icons/leagueColoredCompetition/128/9.png'
                },
                LaLiga:
                {
                   id:"esp.1",
                   imgUrl:'https://images.onefootball.com/icons/leagueColoredCompetition/128/10.png'
                },
                Ligue1:
                {
                   id:"fra.1",
                   imgUrl:'https://images.onefootball.com/icons/leagueColoredCompetition/128/23.png'
                },
                SerieA:
                {
                   id:"ita.1",
                   imgUrl:'https://images.onefootball.com/icons/leagueColoredCompetition/128/13.png'
                },
                Bundesliga:
                {
                   id:"ger.1",
                   imgUrl:'https://images.onefootball.com/icons/leagueColoredCompetition/128/1.png'
                },
                ChampionsLeague:
                {
                   id:2001,
                   imgUrl:'https://upload.wikimedia.org/wikipedia/en/b/bf/UEFA_Champions_League_logo_2.svg'
                },
                EuropaLeague:
                {
                   id:2146,
                   imgUrl:''
                }
 }}
 export default InitialState;